### ISSUE TITLE
Handle missing variables better:

### ISSUE THREAD

**Issue by jayjanssen** [jayjanssen/myq-tools#1]
was from wsrep view

panic: interface conversion: interface is nil, not string

goroutine 16 [running]:
runtime.panic(0x5166e0, 0xc208040fc0)
        /usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
_/vagrant/myqlib.func·010(0xc20802a2a0, 0xc20800fb80, 0x7fe4faf687a8, 0xc2080e51d0)
        /vagrant/myqlib/view_defaults.go:224 +0xa7
_/vagrant/myqlib.FuncCol.Data(0x53bb50, 0x5, 0x553450, 0x1b, 0x5, 0x5746e0, 0xc20802a2a0, 0xc20800fb80)
        /vagrant/myqlib/col.go:229 +0x96
_/vagrant/myqlib.(*FuncCol).Data(0xc2080244e0, 0xc20802a2a0, 0xc20800fb80)
        <autogenerated>:47 +0xa5
_/vagrant/myqlib.NormalView.Data(0xc20804e000, 0x9, 0x9, 0x5494d0, 0x17, 0x5746d8, 0xc20802a2a0, 0xc20800fb80)
        /vagrant/myqlib/view.go:78 +0xec
_/vagrant/myqlib.(*NormalView).Data(0xc2080246c0, 0xc20802a2a0, 0xc20800fb80)
        <autogenerated>:115 +0xa5
main.main()
        /vagrant/myq_status.go:152 +0x1207

**Comment by jayjanssen** [comment]
Maybe wrap an interface on accessing variables so we can handle their absence more gracefully, even in FuncCols
