### ISSUE TITLE
Cleanup for can't connect errors

### ISSUE THREAD

**Issue by jayjanssen** [jayjanssen/myq-tools#18]
# go run myq_status.go -a "-u test" wsrep
panic: Could not write to MySQL command any longer

goroutine 1 [running]:
github.com/jayjanssen/myq-tools/myqlib.func·005()
	/go/src/github.com/jayjanssen/myq-tools/myqlib/loader.go:287 +0xce
github.com/jayjanssen/myq-tools/myqlib.LiveLoader.harvestMySQL(0x3b9aca00, 0x7fff2a7c66cd, 0x7, 0x5c3e10, 0x21, 0x7fb2ba590000, 0x0, 0x0)
	/go/src/github.com/jayjanssen/myq-tools/myqlib/loader.go:291 +0x660
github.com/jayjanssen/myq-tools/myqlib.LiveLoader.getStatus(0x3b9aca00, 0x7fff2a7c66cd, 0x7, 0x522000, 0x0, 0x0)
	/go/src/github.com/jayjanssen/myq-tools/myqlib/loader.go:322 +0x5c
github.com/jayjanssen/myq-tools/myqlib.(*LiveLoader).getStatus(0xc20801e560, 0xc2080340f8, 0x0, 0x0)
	<autogenerated>:90 +0xb3
github.com/jayjanssen/myq-tools/myqlib.GetState(0x7fb2ba5a2040, 0xc20801e560, 0x6a2d50, 0x0, 0x0)
	/go/src/github.com/jayjanssen/myq-tools/myqlib/loader.go:126 +0x232
main.main()
	/vagrant/myq_status.go:143 +0x12f6

goroutine 5 [syscall]:
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35

goroutine 12 [runnable]:
os/exec.func·004(0xc20801ea00)
	/usr/lib/golang/src/os/exec/exec.go:327
created by os/exec.(*Cmd).Start
	/usr/lib/golang/src/os/exec/exec.go:329 +0xb6d

goroutine 9 [chan receive]:
github.com/jayjanssen/myq-tools/myqlib.func·006()
	/go/src/github.com/jayjanssen/myq-tools/myqlib/loader.go:297 +0xb0
created by github.com/jayjanssen/myq-tools/myqlib.LiveLoader.harvestMySQL
	/go/src/github.com/jayjanssen/myq-tools/myqlib/loader.go:300 +0x74d

goroutine 11 [runnable]:
os/exec.(*Cmd).Wait(0xc208058140, 0x0, 0x0)
	/usr/lib/golang/src/os/exec/exec.go:369 +0x30b
github.com/jayjanssen/myq-tools/myqlib.func·008()
	/go/src/github.com/jayjanssen/myq-tools/myqlib/loader.go:311 +0x36
created by github.com/jayjanssen/myq-tools/myqlib.LiveLoader.harvestMySQL
	/go/src/github.com/jayjanssen/myq-tools/myqlib/loader.go:316 +0x8ca
exit status 2

**Comment by jayjanssen** [comment]
# go run myq_status.go -a="-u test" wsrep
ERROR 1045 (28000): Access denied for user 'test'@'localhost' (using password: NO)
exit status 1
